name: ofppt_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  supabase_flutter: ^2.8.0
  webview_flutter: ^4.4.0  
  webview_flutter_android: ^3.0.0
  webview_flutter_wkwebview: ^3.0.0
  url_launcher: ^6.1.14
  printing: ^5.0.0
  flutter_gemini: ^2.0.5
  dash_chat_2: ^0.0.21
  flutter_tawkto: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/